### ISSUE TITLE
Echec de l'import de la base élèves du collège test PILATRE

### ISSUE THREAD

**Issue by Pierre2Maulmont** [betagouv/dossiersco#321]
pas de base chargée.
pas de trace d'envoi de mail dans https://demo.dossiersco.beta.gouv.fr/letter_opener

**Comment by LucienMLD** [comment]
erreur : uninitialized constant TraiterImportsJob::ImportMailer excluded from capture: DSN not set

```
app_1            | [ActiveJob] [TraiterImportsJob] [feb6ad2a-8498-4ab2-b0df-bc27290c1b80] uninitialized constant TraiterImportsJob::ImportMailer excluded from capture: DSN not set
app_1            | [ActiveJob] [TraiterImportsJob] [feb6ad2a-8498-4ab2-b0df-bc27290c1b80] Error performing TraiterImportsJob (Job ID: feb6ad2a-8498-4ab2-b0df-bc27290c1b80) from Async(default) in 106012.91ms: NameError (uninitialized constant TraiterImportsJob::ImportMailer):
app_1            | /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:74:in `block in load_missing_constant'
app_1            | /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
app_1            | /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:74:in `rescue in load_missing_constant'
app_1            | /usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:56:in `load_missing_constant'
app_1            | /app/app/jobs/traiter_imports_job.rb:9:in `perform'
```
